name: FaturaFlow CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl start docker
          sudo docker --version
          docker-compose --version

      - name: Start PostgreSQL container
        run: sudo docker-compose up -d

      - name: Install backend dependencies
        run: npm ci

      - name: Run database migrations
        run: npm run migration:run

      - name: Start backend server
        run: npm run dev &
        env:
          PORT: 3000
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/faturaflow

  build-frontend:
    needs: setup-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  test-cypress:
    needs: build-frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Start frontend server
        run: npm run dev &
        
      - name: Wait for frontend
        run: |
          echo "Waiting for frontend to be ready..."
          npx wait-on http://localhost:5173 --timeout 120000
          echo "Frontend is ready!"

      - name: Wait for backend
        run: |
          echo "Waiting for backend to be ready..."
          npx wait-on http://localhost:3000 --timeout 120000
          echo "Backend is ready!"

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          browser: chrome
          spec: cypress/e2e/testelogin.cy.js
          config: baseUrl=http://localhost:5173
          record: false

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            frontend/cypress/screenshots
            frontend/cypress/videos
          if-no-files-found: ignore