name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: cypress/browsers:node18.12.0-chrome107-ff107
        options: >-
          --entrypoint /bin/sh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm ci

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Start MongoDB (sem autenticação)
        run: |
          docker run -d \
            --name mongodb \
            -p 27017:27017 \
            mongo:6

      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB to be ready..."
          npx wait-on tcp:27017 --timeout 60000

      - name: Start backend
        working-directory: ./backend
        run: npm run dev &
        env:
          PORT: 3000
          DATABASE_URL: mongodb://localhost:27017/faturaflow

      - name: Wait for backend
        run: |
          echo "Waiting for backend..."
          npx wait-on http://localhost:3000 --timeout 60000

      - name: Start frontend
        working-directory: ./frontend
        run: npm run dev &
        env:
          PORT: 5173

      - name: Wait for frontend
        run: |
          echo "Waiting for frontend..."
          npx wait-on http://localhost:5173 --timeout 60000

      - name: Run Cypress tests
        working-directory: ./frontend
        run: npx cypress run
